### ISSUE TITLE
website/admin: implement removing songs from queue

### ISSUE THREAD

**Issue by icxes** [R-a-dio/valkyrie#102]
I'll write about how I think this might work tomorrow since it's late now, just making an issue so I don't forget overnight

j/k forgot about it anyway but the template is done

**Comment by icxes** [comment]
[4f779cd](https://github.com/R-a-dio/valkyrie-themes/commit/4f779cd41118b92d19fc078310f37119120229f8)

**Comment by Wessie** [comment]
added in https://github.com/R-a-dio/valkyrie-themes/commit/f4c2e577a62008111c931a48bf25f3f12d3dfdc3
