### ISSUE TITLE
themes: Click text for action?

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/valkyrie#133]
A lot of pages have features where you can click on a span of text to make some action occur (main page NP title reveals tags, LP page click takes you to a search page with the title in the query, click on title on search page reveals tags).

I don't think this is great. The clickability conflicts with selecting the text, for C+P, and it's not clear from the pointer hover what will actually happen when you click.

I think this should be replaced with dedicated buttons on the side. A button on the right of the NP on main page with a 'tag' icon would tell the user that clicking it reveals the tags. A 'search' icon on a button on the right on the LP page would tell you that it searches. A similar 'tag' icon on the right on the search result entries would also be good.

I think this UI is more discoverable and doesn't break the expectation that text should be selectable, and buttons perform actions.

**Comment by icxes** [comment]
These and more were fixed by Vin in https://github.com/R-a-dio/valkyrie-themes/commit/2dd40a5ee3e74e94c65104da78a25643afbda4e2 and https://github.com/R-a-dio/valkyrie-themes/commit/e6c9b34d586c52990fc60b8c0e68982adb865856
