### ISSUE TITLE
themes: Hover to reveal isn't very good

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/valkyrie#134]
A lot of elements have overflow:hidden and text-overflow:ellipsis. I'm guessing this is what makes text hidden when it's too long and then appear when it's hovered over.

I don't think this is good design; it makes the UI jump around a lot when hovering over elements like LP and queue on the main page. It's better to just fill the box and wrap, making the box vertically larger. I guess it solves the issue with song titles that don't break properly and then escape the box boundary, but there must be better solutions to that than hiding most of the content at all times.

One place where it's also causing render issues seems to be the DJ name. Part of the text is cut off at the bottom when not hovering:
![](https://wessie.info/s/9ea34.png)
![](https://wessie.info/s/5f13.png)
This is obviously minor, but it bothered me.

**Comment by icxes** [comment]
I'm not sure if these were fixed by Vin in https://github.com/R-a-dio/valkyrie-themes/commit/2dd40a5ee3e74e94c65104da78a25643afbda4e2 and https://github.com/R-a-dio/valkyrie-themes/commit/e6c9b34d586c52990fc60b8c0e68982adb865856, please confirm Vin

**Comment by icxes** [comment]
At least most of these were fixed in the above commits and the rest are not happening for me, so I'll close this but keep it in mind.
