### ISSUE TITLE
themes: Excessive whitespace between sections

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/valkyrie#135]
Many sections have too much spacing between elements. Some screenshots:

![](https://wessie.info/s/fb21.png)

![](https://wessie.info/s/a25df.png)

![](https://wessie.info/s/0977.png)

![](https://wessie.info/s/dcf4.png)

**Comment by icxes** [comment]
These and more were fixed by Vin in https://github.com/R-a-dio/valkyrie-themes/commit/2dd40a5ee3e74e94c65104da78a25643afbda4e2 and https://github.com/R-a-dio/valkyrie-themes/commit/e6c9b34d586c52990fc60b8c0e68982adb865856
