### ISSUE TITLE
streamer: Add an option for a dj control mode

### ISSUE THREAD

**Issue by Flaminator** [R-a-dio/valkyrie#15]
Today I was thinking that it would be nice to have a so called "dj control mode" that makes it possible for a dj to use Hanyuu to play it's music from the database.
When in "dj control mode" Hanyuu should probably use a separate playlist than her own to make sure her own queue doesn't get wiped. I guess the playlist can either be controlled using irc but that would spam a lot or one could use a separate api to control the playlist.

**Comment by icxes** [comment]
I don't think this is a necessary feature. @Wessie?
