### ISSUE TITLE
manager: add search index ping

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/valkyrie#32]

**Comment by Wessie** [comment]
When do we actually want to ping the index? and where is it located. We should probably add a generic "update id" to the search interface we haven't defined yet

**Comment by Bevinsky** [comment]
Ideally the index should be pinged whenever a row in tracks is changed.

**Comment by Wessie** [comment]
closed by https://github.com/R-a-dio/valkyrie/pull/61
