### ISSUE TITLE
queue: refresh Song with latest database data before returning it

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/valkyrie#37]

**Comment by Wessie** [comment]
rather than always refreshing a song, we can only refresh if it has been a certain period of time. Any issues with that @Bevinsky ? I've already added a field to the Song type to track when it was read from the database so the data is available to do this instead.

Question then is, what do we consider "stale" data in terms of duration?

**Comment by Bevinsky** [comment]
Isn't it just safer to always refresh it instead? I'm not sure I see the correlation between a certain amount of time passing and the data perhaps being stale. Data being stale isn't a function of time, really.
