### ISSUE TITLE
website: existing routes

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/valkyrie#62]
legacy routes, these all redirect to "stream.r-a-d.io/main":
	

- [x] /main.mp3
- [x] 	/main
- [x] 	/stream.mp3
- [x] 	/stream
- [x] 	/R-a-dio

api routes, some of these might never have been implemented in PHP

- [x] 	GET /api
- [x] 	GET /api/ping
- [x] 	GET /api/song
- [x] 	GET /api/user-cooldown
- [x] 	GET /api/news
- [x] 	GET /api/search
- [x] 	GET /api/metadata
- [x] 	GET /api/can-request
- [x] 	POST /api/request
- [x] 	GET /api/dj-image

public routes
	

- [x] GET /
- [x] 	GET /index
- [x] 	GET /queue
- [x] 	GET /last-played
- [x] 	GET /staff
- [x] 	GET, POST /faves
- [x] 	GET /irc
- [x] 	GET, POST /search
- [x] 	GET, POST /news
- [x] 	GET, POST /login
- [x] 	GET, POST /submit
- [x] 	ANY /set-theme
- [x] 	ANY /logout

private routes
	

- [x] PUT, POST, DELETE /api/dj-image
- [x] 	DELETE /news
- [x] 	GET /admin/
- [x] 	GET /admin/index
- [x] 	GET, POST, PUT, DELETE /admin/news
- [x] 	GET, POST /admin/pending
- [x] 	GET /admin/pending-song
- [x] 	GET /admin/song
- [x] 	GET, POST /admin/songs
- [x] 	GET, POST, PUT, DELETE /admin/users
- [x] 	GET, PUT /admin/profile

**Comment by Bevinsky** [comment]
It might be worth documenting about of which ones are actually used and what they do.

**Comment by Wessie** [comment]
see the [website](https://github.com/R-a-dio/valkyrie/tree/website) branch

**Comment by Wessie** [comment]
Kethsar commented that the android app uses the routes `/api[/{dj-image,news,search}]` so those are the most important to keep functionally the same. I'm unsure if it's worth doing an exact match of the PHP output for all the endpoints. Especially the `meta` key found in a few responses

**Comment by Wessie** [comment]
all routes mentioned in this issue should now exist or have been deemed deprecated and not implemented
