### ISSUE TITLE
website/lastplayed: Add DJ name column to the Last Played sub page

### ISSUE THREAD

**Issue by o-YoY-o** [R-a-dio/valkyrie#81]
Currently in the "Last Played" sub page there's only date and track name. An additional column with the name of the DJ who played the track would be nice. To avoid weirdness with DJ switching I suggest just sticking the name of the DJ who was on while the track begun playing.

**Comment by icxes** [comment]
This isn't really currently tracked in any way, so that will need to be done first, but it sounds like a reasonable feature so I'll get started on the website side and let @Wessie figure out the database side.

**Comment by Wessie** [comment]
Added the field for this in f9b93deb291d16e5b0986b687be88b98927bfc6a. Should let you implement the website rendering part atleast

**Comment by Wessie** [comment]
Should be fully implemented with  1130887, might want to change how it displays without data but that should be pretty rare and I think leaving it empty is fine too
