### ISSUE TITLE
website/search: search issues

### ISSUE THREAD

**Issue by icxes** [R-a-dio/valkyrie#83]
**How to reproduce**: search for any song with a dash in it (e.g. "Creepy Nuts Bling-Bang-Bang-Born", or "Any artist - Any song")
**Expected results**: the search returns song you searched for
**Actual results**: the search returns nothing

**Comment by icxes** [comment]
Searching for "(something)" also gives an error 

> ERR error="Error 1064 (42000): syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'"

**Comment by Wessie** [comment]
This (should) be fixed but it needs some fuzz testing to see if we got all the edgecases

**Comment by Wessie** [comment]
Seems fixed for now, at the cost of having (almost) no functional operators for users to use, but that can be fixed at a later time if we want it

**Comment by icxes** [comment]
Searching for any song with "when" or "the" in the title doesn't seem to work. Seems to stop working already at "wh" or "th".

**Comment by Wessie** [comment]
https://mariadb.com/kb/en/full-text-index-overview/#excluded-results these are just results of how mariadb does text indexing, we probably won't be able to actually change that unless we switch search provider

**Comment by Wessie** [comment]
gonna track this in #90
