### ISSUE TITLE
website/public: issue to track what data is needed for each page

### ISSUE THREAD

**Issue by icxes** [R-a-dio/valkyrie#85]
I'll try to keep this up to date with what data I need passed onto the templates on each page and why, as well as what's already done.

***

**shared**
- [x] Stream URL
- [x] Logged in user
    - Not sure about this yet but might do something with this
- [x] Stream status
    - Mostly for style reasons, but it would be nice to have player controls on the navbar as well (on a dropdown, probably)
- [ ] Last edit date of schedule (and the editor)
    - There needs to be a way for people to tell if the schedule has changed recently

***

**/**
- [x] Queue
- [x] Last Played
- [x] News
- [x] Currently playing DJ

***

**/news**
- [x] News
    - Ideally I'd like these grouped by year so I could make a proper news archive page where you can select a year to show news just for that year, but it's not a particularly important feature

***

**/chat**
- [x] Maybe we should look into alternatives to Kiwi? I don't really use it so I don't know. I can't think of any particular data this page needs.
    - Kiwi is fine for now if nobody has any better ideas

***

**/search**
- [x] List of Songs matching Query
- [x] Pagination
- [x] Time until user's next request
    - Could display this right on the search page (and maybe just disable requesting entirely until it's over) instead of the user having to guess if it's not too much trouble

***

**/schedule**
Related issue: https://github.com/R-a-dio/valkyrie/issues/96
- [x] List of Users that are on the schedule, in the form of something like $weekday: $user
- [x] User's schedule description (can reuse User.DJ.Text?)
- ~~User's timeslot~~
    - They can just put it on the description

***

**/last-played**
- [x] List of last played Songs
- [x] Pagination
- [x] For each song: the DJ that was playing when the song started (see #81)
    - It's a nice idea. Should just be the User so I can grab anything relevant from that.
    - Added in https://github.com/R-a-dio/valkyrie/commit/f9b93deb291d16e5b0986b687be88b98927bfc6a but missing DJ since we don't record that yet (?)

***

**/queue**
- [x] Queue

***

**/favorites**
- [x] List of favourites matching Query

***

**/staff**
- [x] List of Users that are set to be active and visible

***

**/submit**
- [x] Accepted songs
- [x] Declined songs
- [x] Amount of submissions waiting to be declined
- [x] Can submit/time until can submit
    - These seem to be there already, but can't test since submitting songs doesn't work yet
- [ ] (?) The actual songs waiting to be declined
    - If there's no good arguments against it, we might as well show this on the submit page (on a dropdown, maybe). Might reduce the amount of people submitting duplicates (either because they don't know if their submission went through or if something was just released)

***

**Comment by Wessie** [comment]
>shared Stream status

implemented in 743db8f

**Comment by Wessie** [comment]
The remaining missing data here seem all related to the `/schedule` page and should probably get an independent issue to fully track what it requires.

**Comment by icxes** [comment]
Edited some things and added the part about maybe showing the songs on the pending queue on submit page

**Comment by Wessie** [comment]
With the schedule page now implemented, just missing one feature we can track it in https://github.com/R-a-dio/valkyrie/issues/96 instead
