### ISSUE TITLE
irc: add a .kill <djname> feature

### ISSUE THREAD

**Issue by kipukun** [R-a-dio/valkyrie#9]
<Wessie> and it sets dj when the song finishes

**Comment by Wessie** [comment]
while this one makes sense in theory, it does mean the auto-dj won't reconnect if the person that called .kill vanishes. The new `.kill` pings the person that invoked it now, so maybe this isn't needed anymore?

**Comment by kipukun** [comment]
i think the pinging is fine, then. i agree that the ``.dj`` and ``.kill`` commands should be separate entities
